[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-latex/vim-latex'
on_ft = 'tex'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
